"""empty message

Revision ID: 061ed675ef8e
Revises: 
Create Date: 2020-06-16 15:51:22.522139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061ed675ef8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_timestamp'), 'event', ['timestamp'], unique=True)
    op.create_index(op.f('ix_event_type'), 'event', ['type'], unique=False)
    op.create_table('rucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('plants', sa.String(length=120), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rucher_location'), 'rucher', ['location'], unique=True)
    op.create_table('ruche',
    sa.Column('rucher', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('specie', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['rucher'], ['rucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruche_specie'), 'ruche', ['specie'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ruche_specie'), table_name='ruche')
    op.drop_table('ruche')
    op.drop_index(op.f('ix_rucher_location'), table_name='rucher')
    op.drop_table('rucher')
    op.drop_index(op.f('ix_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_timestamp'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
