"""empty message

Revision ID: 06999ee91526
Revises: 3f38bc299085
Create Date: 2020-10-01 10:58:13.670380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06999ee91526'
down_revision = '3f38bc299085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
