"""empty message

Revision ID: 33e5fe79e66c
Revises: 27c871553e40
Create Date: 2020-07-01 17:43:16.894453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e5fe79e66c'
down_revision = '27c871553e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ruche_num'), ['num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ruche_num'), type_='unique')

    # ### end Alembic commands ###
