"""empty message

Revision ID: 3f38bc299085
Revises: 
Create Date: 2020-10-01 10:34:28.129236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f38bc299085'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_registration_date'), ['registration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('rucher',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('plants', sa.String(length=120), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('longit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_rucher_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rucher'))
    )
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rucher_location'), ['location'], unique=False)

    op.create_table('ruche',
    sa.Column('rucher', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('specie', sa.String(length=64), nullable=True),
    sa.Column('age_reine', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rucher'], ['rucher.id'], name=op.f('fk_ruche_rucher_rucher')),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_ruche_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ruche')),
    sa.UniqueConstraint('num', 'user', name='numruche_user_unique')
    )
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruche_age_reine'), ['age_reine'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruche_specie'), ['specie'], unique=False)

    op.create_table('event',
    sa.Column('rucher', sa.Integer(), nullable=True),
    sa.Column('ruche', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['ruche'], ['ruche.id'], name=op.f('fk_event_ruche_ruche')),
    sa.ForeignKeyConstraint(['rucher'], ['rucher.id'], name=op.f('fk_event_rucher_rucher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))

    op.drop_table('event')
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruche_specie'))
        batch_op.drop_index(batch_op.f('ix_ruche_age_reine'))

    op.drop_table('ruche')
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rucher_location'))

    op.drop_table('rucher')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_registration_date'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
