"""empty message

Revision ID: 477ff670926d
Revises: 
Create Date: 2020-06-27 00:11:40.429423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477ff670926d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)

    op.create_table('rucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('plants', sa.String(length=120), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('longit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rucher_location'), ['location'], unique=True)

    op.create_table('ruche',
    sa.Column('rucher', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('specie', sa.String(length=64), nullable=True),
    sa.Column('age_reine', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rucher'], ['rucher.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('num')
    )
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ruche_age_reine'), ['age_reine'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruche_specie'), ['specie'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruche_specie'))
        batch_op.drop_index(batch_op.f('ix_ruche_age_reine'))

    op.drop_table('ruche')
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rucher_location'))

    op.drop_table('rucher')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))

    op.drop_table('event')
    # ### end Alembic commands ###
