"""empty message

Revision ID: 4ed7b3f3d8a0
Revises: c66157101e94
Create Date: 2020-06-18 00:15:20.938121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed7b3f3d8a0'
down_revision = 'c66157101e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rucher', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('rucher', sa.Column('longit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rucher', 'longit')
    op.drop_column('rucher', 'lat')
    # ### end Alembic commands ###
