"""empty message

Revision ID: 5749d01b7744
Revises: 
Create Date: 2020-06-07 23:08:52.974685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5749d01b7744'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruche_specie'), 'ruche', ['specie'], unique=False)
    op.create_table('rucher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('plants', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rucher_location'), 'rucher', ['location'], unique=True)
    op.create_index(op.f('ix_rucher_plants'), 'rucher', ['plants'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rucher_plants'), table_name='rucher')
    op.drop_index(op.f('ix_rucher_location'), table_name='rucher')
    op.drop_table('rucher')
    op.drop_index(op.f('ix_ruche_specie'), table_name='ruche')
    op.drop_table('ruche')
    # ### end Alembic commands ###
