"""empty message

Revision ID: 5dba7149320b
Revises: 477ff670926d
Create Date: 2020-07-01 15:56:30.517271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dba7149320b'
down_revision = '477ff670926d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_index('ix_ruche_age_reine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.create_index('ix_ruche_age_reine', ['age_reine'], unique=False)

    # ### end Alembic commands ###
