"""empty message

Revision ID: 5ecd5f79df40
Revises: ea76e175e41a
Create Date: 2020-08-28 20:55:49.512785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecd5f79df40'
down_revision = 'ea76e175e41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index('ix_event_timestamp')
        batch_op.drop_constraint('fk_event_ruche_ruche', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_event_ruche_ruche'), 'ruche', ['ruche'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_ruche_ruche'), type_='foreignkey')
        batch_op.create_foreign_key('fk_event_ruche_ruche', 'ruche', ['ruche'], ['num'])
        batch_op.create_index('ix_event_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
