"""Add origin column to ruche table

Revision ID: 6ae1a6101e45
Revises: 8898463087a2
Create Date: 2021-02-22 18:24:21.146124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae1a6101e45'
down_revision = '8898463087a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_column('origin')

    # ### end Alembic commands ###
