"""Add Harvest table

Revision ID: 6d05012e3a20
Revises: c7f5cccbc3f0
Create Date: 2021-09-01 16:46:00.141163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d05012e3a20'
down_revision = 'c7f5cccbc3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('supers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['event.id'], name=op.f('fk_harvest_event_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harvest'))
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('harvest')
    # ### end Alembic commands ###
