"""empty message

Revision ID: 752288d29baf
Revises: fb750d1d162a
Create Date: 2020-11-26 21:29:08.370522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752288d29baf'
down_revision = 'fb750d1d162a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
