"""empty message

Revision ID: 7c483675d30e
Revises: 4ed7b3f3d8a0
Create Date: 2020-06-25 23:32:51.156945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c483675d30e'
down_revision = '4ed7b3f3d8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ruche', ['num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ruche', type_='unique')
    # ### end Alembic commands ###
