"""Housekeeping: remove rucher.feedback and ruche.specie columns

Revision ID: 8898463087a2
Revises: b5ad56087ecf
Create Date: 2021-01-28 23:28:06.479442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8898463087a2'
down_revision = 'b5ad56087ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_index('ix_ruche_specie')
        batch_op.drop_column('specie')

    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_ruche_specie', ['specie'], unique=False)

    # ### end Alembic commands ###
