"""empty message

Revision ID: 8df417d64820
Revises: 5749d01b7744
Create Date: 2020-06-11 22:58:57.945486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df417d64820'
down_revision = '5749d01b7744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rucher', sa.Column('feedback', sa.Text(), nullable=True))
    op.drop_index('ix_rucher_plants', table_name='rucher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rucher_plants', 'rucher', ['plants'], unique=False)
    op.drop_column('rucher', 'feedback')
    # ### end Alembic commands ###
