"""empty message

Revision ID: b5ad56087ecf
Revises: 9806f2dd265e
Create Date: 2021-01-28 21:49:32.978727

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b5ad56087ecf'
down_revision = '9806f2dd265e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # with op.batch_alter_table('ruche', schema=None) as batch_op:
    #     batch_op.drop_index('ix_ruche_specie')
    #     batch_op.drop_column('specie')

    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_rucher_specie'), ['specie'], unique=False)

    op.execute("""
        UPDATE rucher
        SET specie = tmp.ruche_min
        FROM (select min(ruche.specie) as ruche_min, ruche.rucher AS rucher_id from ruche group by ruche.rucher) AS tmp
        WHERE tmp.rucher_id = rucher.id
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rucher_specie'))
        batch_op.drop_column('specie')

    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_ruche_specie', ['specie'], unique=False)

    # ### end Alembic commands ###
