"""empty message

Revision ID: db3c7286dce3
Revises: 6764a8ce5e38
Create Date: 2020-08-24 17:43:02.714836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3c7286dce3'
down_revision = '6764a8ce5e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('numruche_user_unique', ['num', 'user'])
        batch_op.drop_constraint('uq_ruche_num', type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_ruche_user_users'), 'users', ['user'], ['id'])

    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_rucher_location')
        batch_op.create_index(batch_op.f('ix_rucher_location'), ['location'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_rucher_user_users'), 'users', ['user'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rucher_user_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_rucher_location'))
        batch_op.create_index('ix_rucher_location', ['location'], unique=1)
        batch_op.drop_column('user')

    with op.batch_alter_table('ruche', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ruche_user_users'), type_='foreignkey')
        batch_op.create_unique_constraint('uq_ruche_num', ['num'])
        batch_op.drop_constraint('numruche_user_unique', type_='unique')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
