"""empty message

Revision ID: ea76e175e41a
Revises: db3c7286dce3
Create Date: 2020-08-24 17:49:46.218938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea76e175e41a'
down_revision = 'db3c7286dce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_registration_date'), ['registration_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_registration_date'))
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
