"""Rename frelons_asiats to frelons_asiat

Revision ID: fb750d1d162a
Revises: 06999ee91526
Create Date: 2020-10-18 22:46:12.168027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb750d1d162a'
down_revision = '06999ee91526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frelons_asiat', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rucher', schema=None) as batch_op:
        batch_op.drop_column('frelons_asiat')

    # ### end Alembic commands ###
